name: frontend_mirrorer

# version: 1.0.0

on:
  push:
      branches:
          - 'main'
      paths:
          - 'app/front/web/**'

env:
    SOURCE: bazar-de-komi/terarea
    MIRROR_URL: "Hanra-s-work/ifttt"
    GITHUB_SSH_KEY: ${{ secrets.AREA_SITE }}

jobs:
    push_to_mirror:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Push the content to the mirror repository
          uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url: git@github.com:${{ env.MIRROR_URL }}.git
            ssh_private_key: ${{ env.GITHUB_SSH_KEY }}
